export const AUDIT_ACTIONS = Object.freeze({
    LOGIN: 'LOGIN',

    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    RESTORE_USER: 'RESTORE_USER',

    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
})