export const ERROR_CODES = Object.freeze({
    // User
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_USER_ID: 'INVALID_USER_ID',
    INVALID_REQUEST: 'INVALID_REQUEST',
    MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',

    // Auth (future)
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',

    // Generic
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',

    // System
    DATABASE_ERROR: 'DATABASE_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
})